const TranslateView = {
    'pt-BR': {
        appearance: 'Aparência',
        theme: 'Tema',
        light: 'Claro',
        dark: 'Escuro',
        fontSize: 'Tamanho da Fonte',
        small: 'Pequena',
        medium: 'Média',
        large: 'Grande',
        language: 'Idioma do Sistema',
        selectFontSize: 'Selecione o tamanho da fonte',
        selectLanguage: 'Selecione o idioma',
        currencyFormat: 'Formato de Moeda',
        selectCurrency: 'Selecione a moeda',
        notification: 'Notificações',
        lowStockAlert: 'Alerta de Estoque Baixo',
    },
    'en-US': {
        appearance: 'Appearance',
        theme: 'Theme',
        light: 'Light',
        dark: 'Dark',
        fontSize: 'Font Size',
        small: 'Small',
        medium: 'Medium',
        large: 'Large',
        language: 'System Language',
        selectFontSize: 'Select font size',
        selectLanguage: 'Select language',
        currencyFormat: 'Currency Format',
        selectCurrency: 'Select currency',
        notification: 'Notifications',
        lowStockAlert: 'Low Stock Alert',
    },
    'es': {
        appearance: 'Apariencia',
        theme: 'Tema',
        light: 'Claro',
        dark: 'Oscuro',
        fontSize: 'Tamaño de Fuente',
        small: 'Pequeña',
        medium: 'Mediana',
        large: 'Grande',
        language: 'Idioma del Sistema',
        selectFontSize: 'Seleccione el tamaño de fuente',
        selectLanguage: 'Seleccione el idioma',
        currencyFormat: 'Formato de Moneda',
        selectCurrency: 'Seleccione la moneda',

        notification: 'Notificaciones',
        lowStockAlert: 'Alerta de Stock Bajo',
    }
}

export default TranslateView;